---
title: Package index
---

## Prepare data, kinetics models, and noise parameters for analysis

- [as_pop_data()](man/as_pop_data.qmd): Load a cross-sectional antibody survey data set
- [load_pop_data()](man/load_pop_data.qmd): Load a cross-sectional antibody survey data set
- [as_sr_params()](man/as_sr_params.qmd): Load longitudinal seroresponse parameters
- [load_sr_params()](man/load_sr_params.qmd): Load longitudinal seroresponse parameter samples
- [as_noise_params()](man/as_noise_params.qmd): Load noise parameters
- [load_noise_params()](man/load_noise_params.qmd): Load noise parameters
- [check_pop_data()](man/check_pop_data.qmd): Check the formatting of a cross-sectional antibody survey dataset.
- [strata()](man/strata.qmd): Extract `Strata` metadata from an object

## Extract information from data, seroresponse models, and noise parameters

- [get_biomarker_levels()](man/get_biomarker_levels.qmd): Extract biomarker levels
- [get_biomarker_names_var()](man/get_biomarker_names_var.qmd): Get biomarker variable name
- [get_values_var()](man/get_values_var.qmd): Extract antibody measurement values
- [get_values()](man/get_values.qmd): Get antibody measurement values

## Visualize data

- [autoplot.pop_data()](man/autoplot.pop_data.qmd): Plot distribution of antibodies
- [autoplot.curve_params()](man/autoplot.curve_params.qmd): Graph antibody decay curves by antigen isotype
- [graph.curve.params()](man/graph.curve.params.qmd): Graph estimated antibody decay curves
- [graph_loglik()](man/graph_loglik.qmd): Graph log-likelihood of data
- [log_likelihood()](man/log_likelihood.qmd): Calculate log-likelihood
- [antibody_decay_curve()](man/antibody_decay_curve.qmd): Antibody decay curve with natural parameters
- [pathogen_decay_curve()](man/pathogen_decay_curve.qmd): Pathogen decay curve
- [plot_decay_curve()](man/plot_decay_curve.qmd): Plot a decay function
- [curve_app()](man/curve_app.qmd): Launch the interactive Shiny app for the antigen-antibody kinetics model
- [t1f()](man/t1f.qmd): Calculate time to end of active infection
- [y1f()](man/y1f.qmd): Calculate peak antibody concentration

## Estimate seroconversion incidence rates

- [est_seroincidence()](man/est_seroincidence.qmd): Find the maximum likelihood estimate of the incidence rate parameter
- [est_seroincidence_by()](man/est_seroincidence_by.qmd): Estimate Seroincidence

## Summarize seroconversion incidence rate estimates

- [summary.seroincidence()](man/summary.seroincidence.qmd): Summarizing fitted seroincidence models
- [summary.seroincidence.by()](man/summary.seroincidence.by.qmd): Summary Method for `"seroincidence.by"` Objects

## Visualize seroconversion incidence rate estimates

- [autoplot.seroincidence()](man/autoplot.seroincidence.qmd): Plot the log-likelihood curve for the incidence rate estimate
- [autoplot.seroincidence.by()](man/autoplot.seroincidence.by.qmd): Plot `seroincidence.by` log-likelihoods
- [autoplot.summary.seroincidence.by()](man/autoplot.summary.seroincidence.by.qmd): Plot method for `summary.seroincidence.by` objects

## Compare seroconversion incidence rates

- [compare_seroincidence()](man/compare_seroincidence.qmd): Compare seroincidence rates between two groups

## Example data sets

- [sees_pop_data_100](man/sees_pop_data_100.qmd): Small example cross-sectional data set
- [sees_pop_data_pk_100](man/sees_pop_data_pk_100.qmd): Small example cross-sectional data set
- [typhoid_curves_nostrat_100](man/typhoid_curves_nostrat_100.qmd): Small example of antibody response curve parameters for typhoid
- [example_noise_params_sees](man/example_noise_params_sees.qmd): Small example of noise parameters for typhoid
- [example_noise_params_pk](man/example_noise_params_pk.qmd): Small example of noise parameters for typhoid
- [sees_typhoid_ests_strat](man/sees_typhoid_ests_strat.qmd): Example `"seroincidence.by"` object
- [serocalculator_example()](man/serocalculator_example.qmd): Get path to an example file

## Simulate data sets

- [sim_pop_data()](man/sim_pop_data.qmd): Simulate a cross-sectional serosurvey with noise
- [sim_pop_data_multi()](man/sim_pop_data_multi.qmd): Simulate multiple data sets
- [analyze_sims()](man/analyze_sims.qmd): Analyze simulation results
- [autoplot.sim_results()](man/autoplot.sim_results.qmd): Plot simulation results `autoplot()` method for `sim_results` objects
