coverage:
  status:
    project: # add everything under here, more options at
     # https://docs.codecov.com/docs/commit-status
      default:
        # basic
        target: auto # default
        threshold: 1%
        base: auto
        informational: false # default
    patch:
      default:
        target: auto
        threshold: 1%
        informational: false
