project:
  type: website
  output-dir: ../docs/
execute:
  freeze: auto
bibliography: vignettes/references.bib
website:
  title: serocalculator
  repo-url: https://github.com/UCD-SERG/serocalculator
  repo-actions:
    - edit
    - source
    - issue
  navbar:
    search: true
    pinned: false
    right:
      - icon: github
        href: https://github.com/UCD-SERG/serocalculator
        aria-label: View serocalculator on GitHub
    left:
      - text: Documentation
        file: man/serocalculator-package.qmd
      - text: Articles
        menu:
          - text: '---Get started---'
          - text: Get started with serocalculator
            file: vignettes/articles/serocalculator.Rmd
          - text: '---Methodology---'
          - text: Methodology
            file: vignettes/methodology.qmd
          - text: Simulate cross-sectional data
            file: vignettes/articles/simulate_xsectionalData.qmd
          - text: '---Examples---'
          - text: Enteric fever example
            file: vignettes/articles/enteric_fever_example.Rmd
          - text: Scrub typhus example
            file: vignettes/articles/scrubTyphus_example.Rmd
  sidebar:
    collapse-level: 1
    contents:
      - text: Home
        file: index.qmd
        style: floating
      - section: Articles
        style: floating
        contents:
          - section: Get started
            contents:
              - vignettes/articles/serocalculator.Rmd
          - section: Methodology
            contents:
              - vignettes/methodology.qmd
              - vignettes/articles/simulate_xsectionalData.qmd
          - section: Examples
            contents:
              - vignettes/articles/enteric_fever_example.Rmd
              - vignettes/articles/scrubTyphus_example.Rmd
      - section: Reference
        contents:
          - text: analyze_sims
            file: man/analyze_sims.qmd
          - text: as_noise_params
            file: man/as_noise_params.qmd
          - text: as_pop_data
            file: man/as_pop_data.qmd
          - text: as_sr_params
            file: man/as_sr_params.qmd
          - text: autoplot.curve_params
            file: man/autoplot.curve_params.qmd
          - text: autoplot.pop_data
            file: man/autoplot.pop_data.qmd
          - text: autoplot.seroincidence.by
            file: man/autoplot.seroincidence.by.qmd
          - text: autoplot.seroincidence
            file: man/autoplot.seroincidence.qmd
          - text: autoplot.sim_results
            file: man/autoplot.sim_results.qmd
          - text: autoplot.summary.seroincidence.by
            file: man/autoplot.summary.seroincidence.by.qmd
          - text: check_pop_data
            file: man/check_pop_data.qmd
          - text: compare_seroincidence
            file: man/compare_seroincidence.qmd
          - text: est_seroincidence_by
            file: man/est_seroincidence_by.qmd
          - text: est_seroincidence
            file: man/est_seroincidence.qmd
          - text: example_noise_params_pk
            file: man/example_noise_params_pk.qmd
          - text: example_noise_params_sees
            file: man/example_noise_params_sees.qmd
          - text: get_biomarker_levels
            file: man/get_biomarker_levels.qmd
          - text: get_biomarker_names_var
            file: man/get_biomarker_names_var.qmd
          - text: get_values_var
            file: man/get_values_var.qmd
          - text: get_values
            file: man/get_values.qmd
          - text: graph_loglik
            file: man/graph_loglik.qmd
          - text: graph.curve.params
            file: man/graph.curve.params.qmd
          - text: load_noise_params
            file: man/load_noise_params.qmd
          - text: load_pop_data
            file: man/load_pop_data.qmd
          - text: load_sr_params
            file: man/load_sr_params.qmd
          - text: log_likelihood
            file: man/log_likelihood.qmd
          - text: sees_pop_data_100
            file: man/sees_pop_data_100.qmd
          - text: sees_pop_data_pk_100
            file: man/sees_pop_data_pk_100.qmd
          - text: sees_typhoid_ests_strat
            file: man/sees_typhoid_ests_strat.qmd
          - text: serocalculator_example
            file: man/serocalculator_example.qmd
          - text: sim_pop_data_multi
            file: man/sim_pop_data_multi.qmd
          - text: sim_pop_data
            file: man/sim_pop_data.qmd
          - text: strata
            file: man/strata.qmd
          - text: summary.seroincidence.by
            file: man/summary.seroincidence.by.qmd
          - text: summary.seroincidence
            file: man/summary.seroincidence.qmd
          - text: typhoid_curves_nostrat_100
            file: man/typhoid_curves_nostrat_100.qmd
      - text: News
        file: NEWS.md
      - text: Code of conduct
        file: CODE_OF_CONDUCT.md
      - text: Contributing
        file: CONTRIBUTING.md
format:
  html:
    code-link: true
    theme:
      light: default
      dark: darkly
    css: styles.css
    number-sections: false
    code-fold: show
    echo: true
    code-copy: true
    code-overflow: scroll
    title-block-style: none
    toc: true
    grid:
      sidebar-width: 340px
      margin-width: 340px
