---
title: "example-analysis"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{example-analysis}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(seroincidence)
library(Hmisc)
```

```{r "load data"}

# load longitudinal parameter MC sample
system.file("extdata", "pertussis-iggpt2.rda", package = "seroincidence") |> load() # output: longpar.mc
lp = longpar.mc$IgG
day2yr <- 365.25;
ln.pars <- data.frame(
  y1=lp$y1,               # peak levels
  alpha=day2yr*lp$alpha,  # decay rate (per year)
  d=lp$r -1);             # shape (r-1 offset from exp)

#read simulated data
raw.data = system.file("extdata", "SimulDat.txt", package = "seroincidence") |> read.table(head=TRUE)

```

```{r}
cat.bnd = seq(0,80,by=5); n.cats = length(cat.bnd)-1; # define age categories
age.cat = rep(NA,length(raw.data$AGE))
for(i in 1:length(cat.bnd-1)) age.cat[(raw.data$AGE >= cat.bnd[i])
  & (raw.data$AGE < cat.bnd[i+1])] <- i
clean.data = data.frame(age=floor(raw.data$AGE)+0.5,IgG=raw.data$IgG,cat=age.cat)

# define global parameters
cond <- data.frame(nu=2.5,                    # B noise
  eps=0.3,                   # M noise
  y.low=2.5,                 # low cutoff
  y.high=5e4);               # high cutoff

lambda = 0.015 # initial estimate: starting value
log.lambda = log(lambda)
log.lmin=log(lambda/10);log.lmax=log(10*lambda)   # seroincidence rate interval
log.lambda.est=matrix(0, nrow=n.cats, ncol=6,
  dimnames = list(rep("",n.cats),
    c("","ml.est", "lwr0.05", "upr0.95",
      "LLF","N iter.")))
# loop over age categories
system.time(
  for (k.cat in 1:n.cats)                       # per age category
  { cat(k.cat,"\n")
    y.cat = as.vector(subset(clean.data,subset=clean.data$cat==as.character(k.cat),
      select="IgG"))$IgG;
    a.cat = as.vector(subset(clean.data,subset=clean.data$cat==as.character(k.cat),
      select="age"))$age;
    cs.data <- data.frame(y=y.cat, a=a.cat);
    objfunc <- function(llam){
      # add terms, e.g. for other antibodies
      # res < fdev(llam,cs1,ln1,cond1) + fdev(llam,cs2,ln2,cond2) + ...
      # return(res)
      return(fdev(llam,cs.data,ln.pars,cond));
    }
    # seroincidence estimation
    
    fit = nlm(objfunc,log.lambda,
      hessian=TRUE,print.level=0,stepmax=(log.lmax-log.lmin)/4);
    
    log.lambda.est[k.cat,] = c(k.cat,
      fit$estimate,
      fit$estimate + qnorm(c(0.05))*sqrt(1/fit$hessian),
      fit$estimate + qnorm(c(0.95))*sqrt(1/fit$hessian),
      fit$minimum,
      fit$iterations)
    
    log.lambda=log.lambda.est[k.cat,2]
  })

```

```{r}
# check results in log.lambda.est:
pander::pander(log.lambda.est)

```

