## Graph antibody decay curves by antigen isotype {.unnumbered}


### Description

Graph antibody decay curves by antigen isotype



### Usage

<pre><code class='language-R'>## S3 method for class 'curve_params'
autoplot(
  object,
  method = c("graph.curve.params", "graph_seroresponse_model_1"),
  ...
)
</code></pre>


### Arguments

<table role = "presentation">
<tr><td style = "white-space: collapse; font-family: monospace; vertical-align: top"><code id="object">object</code></td>
<td>
a <code>curve_params</code> object (constructed using <code>as_sr_params()</code>), which is
a <code>data.frame()</code> containing MCMC samples of antibody decay curve parameters
</td></tr>
<tr><td style = "white-space: collapse; font-family: monospace; vertical-align: top"><code id="method">method</code></td>
<td>
a character string indicating whether to use


<ul>
<li> <code>graph.curve.params()</code> (default) or

</li>
<li> <code>graph_seroresponse_model_1()</code> (previous default)
as the graphing method.

</li></ul>
</td></tr>
<tr><td style = "white-space: collapse; font-family: monospace; vertical-align: top"><code id="...">...</code></td>
<td>
additional arguments passed to the sub-function
indicated by the <code>method</code> argument.
</td></tr>
</table>


### Details

Currently, the backend for this method is <code>graph.curve.params()</code>.
Previously, the backend for this method was <code>graph_seroresponse_model_1()</code>.
That function is still available if preferred.



### Value

a <code>ggplot2::ggplot()</code> object



### Examples
```{r, warning=FALSE, message=FALSE, eval=TRUE}
library("serocalculator")


library(dplyr)
library(ggplot2)
library(magrittr)

curve <-
  serocalculator_example("example_curve_params.csv") |>
  read.csv() |>
  as_sr_params() |>
  filter(antigen_iso %in% c("HlyE_IgA", "HlyE_IgG")) |>
  autoplot()

curve



```
