## Plot method for <code>summary.seroincidence.by</code> objects {.unnumbered}


### Description

Plot method for <code>summary.seroincidence.by</code> objects



### Usage

<pre><code class='language-R'>## S3 method for class 'summary.seroincidence.by'
autoplot(object, type, ...)
</code></pre>


### Arguments

<table role = "presentation">
<tr><td style = "white-space: collapse; font-family: monospace; vertical-align: top"><code id="object">object</code></td>
<td>
a <code>summary.seroincidence.by</code> object
(generated by applying the <code>summary()</code>
method to the output of <code>est_seroincidence_by()</code>).
</td></tr>
<tr><td style = "white-space: collapse; font-family: monospace; vertical-align: top"><code id="type">type</code></td>
<td>
character string indicating which type of plot to generate.
The implemented options are:


<ul>
<li> <code>"scatter"</code>: calls <code>strat_ests_scatterplot()</code> to generate a scatterplot

</li>
<li> <code>"bar"</code>: calls <code>strat_ests_barplot()</code> to generate a barplot

</li></ul>
</td></tr>
<tr><td style = "white-space: collapse; font-family: monospace; vertical-align: top"><code id="...">...</code></td>
<td>

Arguments passed on to <code>strat_ests_scatterplot</code>, <code>strat_ests_barplot</code>


<dl>
<dt><code>xvar</code></dt><dd>the name of a stratifying variable in <code>object</code>
</dd>
<dt><code>alpha</code></dt><dd>transparency for the points in the graph
(1 = no transparency, 0 = fully transparent)
</dd>
<dt><code>shape</code></dt><dd>shape argument for <code>geom_point()</code>
</dd>
<dt><code>dodge_width</code></dt><dd>width for jitter
</dd>
<dt><code>CIs</code></dt><dd>logical, if <code>TRUE</code>, add CI error bars
</dd>
<dt><code>color_var</code></dt><dd>character which variable in <code>object</code> to use
to determine point color
</dd>
<dt><code>group_var</code></dt><dd>character which variable in <code>object</code> to use
to connect points with lines (<code>NULL</code> for no lines)
</dd>
<dt><code>yvar</code></dt><dd>the name of a stratifying variable in <code>object</code>.
</dd>
<dt><code>title</code></dt><dd>a title for the final plot.
</dd>
<dt><code>xlab</code></dt><dd>a label for the x-axis of the final plot.
</dd>
<dt><code>ylab</code></dt><dd>a label for the y-axis of the final plot.
</dd>
<dt><code>fill_lab</code></dt><dd>fill label.
</dd>
<dt><code>color_palette</code></dt><dd>optional color palette for bar color.
</dd>
</dl>
</td></tr>
</table>


### Value

a <code>ggplot2::ggplot()</code> object



### Examples
```{r, warning=FALSE, message=FALSE, eval=TRUE}
library("serocalculator")


library(dplyr)
library(ggplot2)

xs_data <-
  sees_pop_data_pk_100

curve <-
  typhoid_curves_nostrat_100 %>%
  filter(antigen_iso %in% c("HlyE_IgA", "HlyE_IgG"))

noise <-
  example_noise_params_pk

est2 <- est_seroincidence_by(
  strata = c("catchment", "ageCat"),
  pop_data = xs_data,
  sr_params = curve,
  noise_params = noise,
  curve_strata_varnames= NULL,
  noise_strata_varnames = NULL,
  antigen_isos = c("HlyE_IgG", "HlyE_IgA"),
  num_cores = 2 # Allow for parallel processing to decrease run time
)

est2sum <- summary(est2)

est2sum |> autoplot(
    type ="scatter",
    xvar = "ageCat",
    color_var = "catchment",
    CIs = TRUE,
    group_var = "catchment")

est2sum |> autoplot(
    type = "bar",
    yvar = "ageCat",
    color_var = "catchment",
    CIs = TRUE)



```
