## Compare seroincidence rates between two groups {.unnumbered}


### Description

Perform a two-sample z-test to compare seroincidence rates between
two groups. Since we use maximum likelihood estimation (MLE) for each
seroincidence estimate and estimates from different strata or data sets
are uncorrelated, we can use a simple two-sample z-test using the
Gaussian distribution. The standard error for the difference is computed
by adding the estimated variances and taking the square root.



### Usage

<pre><code class='language-R'>compare_seroincidence(x, y = NULL, coverage = 0.95, verbose = FALSE, ...)

## S3 method for class 'seroincidence'
compare_seroincidence(x, y = NULL, coverage = 0.95, verbose = FALSE, ...)

## S3 method for class 'seroincidence.by'
compare_seroincidence(x, y = NULL, coverage = 0.95, verbose = FALSE, ...)
</code></pre>


### Arguments

<table role = "presentation">
<tr><td style = "white-space: collapse; font-family: monospace; vertical-align: top"><code id="x">x</code></td>
<td>
A <code>"seroincidence"</code> object from <code>est_seroincidence()</code> or
a <code>"seroincidence.by"</code> object from <code>est_seroincidence_by()</code>
</td></tr>
<tr><td style = "white-space: collapse; font-family: monospace; vertical-align: top"><code id="y">y</code></td>
<td>
A <code>"seroincidence"</code> object from <code>est_seroincidence()</code>
(optional if <code>x</code> is a <code>"seroincidence.by"</code> object)
</td></tr>
<tr><td style = "white-space: collapse; font-family: monospace; vertical-align: top"><code id="coverage">coverage</code></td>
<td>
Desired confidence interval coverage probability
(default = 0.95)
</td></tr>
<tr><td style = "white-space: collapse; font-family: monospace; vertical-align: top"><code id="verbose">verbose</code></td>
<td>
Logical indicating whether to print verbose messages
(default = FALSE)
</td></tr>
<tr><td style = "white-space: collapse; font-family: monospace; vertical-align: top"><code id="...">...</code></td>
<td>
Additional arguments (currently unused)
</td></tr>
</table>


### Details

When comparing two single <code>"seroincidence"</code> objects, this function performs a
two-sample z-test and returns results in the standard <code>htest</code> format.

When applied to a <code>"seroincidence.by"</code> object (stratified estimates),
the function compares all pairs of strata and returns a nicely formatted
table with point estimates for the difference in seroincidence, p-values,
and confidence intervals.

The test statistic is computed as:

<p style="text-align: center;">$z = \frac{\lambda_1 - \lambda_2}{\sqrt{SE_1^2 + SE_2^2}}$


where $\lambda_1$ and $\lambda_2$ are the estimated incidence rates,
and $SE_1$ and $SE_2$ are their standard errors.



### Value


<ul>
<li> When comparing two <code>"seroincidence"</code> objects: An object of class
<code>"htest"</code> containing the test statistic, p-value, confidence interval,
and estimates.

</li>
<li> When applied to a <code>"seroincidence.by"</code> object: A <code>tibble::tibble()</code>
with columns for each pair of strata, the difference in incidence rates,
standard error, z-statistic, p-value, and confidence interval bounds.

</li></ul>



### Methods (by class)


<ul>
<li> <code>compare_seroincidence(seroincidence)</code>: Compare two single seroincidence
estimates

</li>
<li> <code>compare_seroincidence(seroincidence.by)</code>: Compare all pairs of stratified
seroincidence estimates

</li></ul>


### Examples
```{r, warning=FALSE, message=FALSE, eval=FALSE}
library("serocalculator")

# See inst/examples/exm-compare_seroincidence.R for complete examples



```
