## Small example of noise parameters for typhoid {.unnumbered}


### Description

A subset of noise parameter estimates from the SEES study,
for examples and testing.



### Usage

<pre><code class='language-R'>example_noise_params_sees
</code></pre>


### Format



<h4><code>example_noise_params_pk</code></h4>

A <code>curve_params</code> object (from <code>as_sr_params()</code>) with 4 rows and 7 columns:


<dl>
<dt>antigen_iso</dt><dd>which antigen and isotype are being measured
(data is in long format)
</dd>
<dt>Country</dt><dd>Location for which the noise parameters were estimated
</dd>
<dt>y.low</dt><dd>Lower limit of detection
</dd>
<dt>eps</dt><dd>Measurement noise, defined by a CV (coefficient of variation)
as the ratio of the standard deviation to the mean for replicates.
Note that the CV should ideally be measured across plates
rather than within the same plate.
</dd>
<dt>nu</dt><dd>Biological noise: error from
cross-reactivity to other antibodies.
It is defined as the 95th percentile of
the distribution of antibody responses to the antigen-isotype
in a population with no exposure.
</dd>
<dt>y.high</dt><dd>Upper limit of detection
</dd>
<dt>Lab</dt><dd>Lab for which noise was estimated.
</dd>
</dl>




### Source

<a href="https://osf.io/rtw5k">https://osf.io/rtw5k</a>


