## Graph log-likelihood of data {.unnumbered}


### Description

Graph log-likelihood of data



### Usage

<pre><code class='language-R'>graph_loglik(
  pop_data,
  curve_params,
  noise_params,
  antigen_isos = pop_data %&gt;% get_biomarker_levels(),
  x = 10^seq(-3, 0, by = 0.1),
  highlight_points = NULL,
  highlight_point_names = "highlight_points",
  log_x = FALSE,
  previous_plot = NULL,
  curve_label = paste(antigen_isos, collapse = " + "),
  ...
)
</code></pre>


### Arguments

<table role = "presentation">
<tr><td style = "white-space: collapse; font-family: monospace; vertical-align: top"><code id="pop_data">pop_data</code></td>
<td>
a <code>data.frame()</code> with cross-sectional serology data
by antibody and age, and additional columns
</td></tr>
<tr><td style = "white-space: collapse; font-family: monospace; vertical-align: top"><code id="curve_params">curve_params</code></td>
<td>
a <code>data.frame()</code> containing MCMC samples of parameters
from the Bayesian posterior distribution of a longitudinal decay curve model.
The parameter columns must be named:


<ul>
<li> <code>antigen_iso</code>: a <code>character()</code> vector indicating antigen-isotype
combinations

</li>
<li> <code>iter</code>: an <code>integer()</code> vector indicating MCMC sampling iterations

</li>
<li> <code>y0</code>: baseline antibody level at \$t=0\$ (\$y(t=0)\$)

</li>
<li> <code>y1</code>: antibody peak level (ELISA units)

</li>
<li> <code>t1</code>: duration of infection

</li>
<li> <code>alpha</code>: antibody decay rate
(1/days for the current longitudinal parameter sets)

</li>
<li> <code>r</code>: shape factor of antibody decay

</li></ul>
</td></tr>
<tr><td style = "white-space: collapse; font-family: monospace; vertical-align: top"><code id="noise_params">noise_params</code></td>
<td>
a <code>data.frame()</code> (or <code>tibble::tibble()</code>)
containing the following variables,
specifying noise parameters for each antigen isotype:


<ul>
<li> <code>antigen_iso</code>: antigen isotype whose noise parameters are being specified
on each row

</li>
<li> <code>nu</code>: biological noise

</li>
<li> <code>eps</code>: measurement noise

</li>
<li> <code>y.low</code>: lower limit of detection for the current antigen isotype

</li>
<li> <code>y.high</code>: upper limit of detection for the current antigen isotype

</li></ul>
</td></tr>
<tr><td style = "white-space: collapse; font-family: monospace; vertical-align: top"><code id="antigen_isos">antigen_isos</code></td>
<td>
Character vector listing one or more antigen isotypes.
Values must match <code>pop_data</code>.
</td></tr>
<tr><td style = "white-space: collapse; font-family: monospace; vertical-align: top"><code id="x">x</code></td>
<td>
sequence of lambda values to graph
</td></tr>
<tr><td style = "white-space: collapse; font-family: monospace; vertical-align: top"><code id="highlight_points">highlight_points</code></td>
<td>
a possible highlighted value
</td></tr>
<tr><td style = "white-space: collapse; font-family: monospace; vertical-align: top"><code id="highlight_point_names">highlight_point_names</code></td>
<td>
labels for highlighted points
</td></tr>
<tr><td style = "white-space: collapse; font-family: monospace; vertical-align: top"><code id="log_x">log_x</code></td>
<td>
should the x-axis be on a logarithmic scale (<code>TRUE</code>)
or linear scale (<code>FALSE</code>, default)?
</td></tr>
<tr><td style = "white-space: collapse; font-family: monospace; vertical-align: top"><code id="previous_plot">previous_plot</code></td>
<td>
if not NULL, the current data is added to the
existing graph
</td></tr>
<tr><td style = "white-space: collapse; font-family: monospace; vertical-align: top"><code id="curve_label">curve_label</code></td>
<td>
if not NULL, add a label for the curve
</td></tr>
<tr><td style = "white-space: collapse; font-family: monospace; vertical-align: top"><code id="...">...</code></td>
<td>

Arguments passed on to <code>log_likelihood</code>


<dl>
<dt><code>verbose</code></dt><dd>logical: if TRUE, print verbose log information to console
</dd>
</dl>
</td></tr>
</table>


### Value

a <code>ggplot2::ggplot()</code>



### Examples
```{r, warning=FALSE, message=FALSE, eval=TRUE}
library("serocalculator")


library(dplyr)
library(tibble)

# Load cross-sectional data
xs_data <-
  sees_pop_data_pk_100

# Load curve parameters and subset for the purposes of this example
curve <-
  typhoid_curves_nostrat_100 %>%
  filter(antigen_iso %in% c("HlyE_IgA", "HlyE_IgG"))

# Load noise parameters
cond <- tibble(
  antigen_iso = c("HlyE_IgG", "HlyE_IgA"),
  nu = c(0.5, 0.5),                          # Biologic noise (nu)
  eps = c(0, 0),                             # M noise (eps)
  y.low = c(1, 1),                           # Low cutoff (llod)
  y.high = c(5e6, 5e6))                      # High cutoff (y.high)

# Graph the log likelihood
lik_HlyE_IgA <- # nolint: object_name_linter
  graph_loglik(
    pop_data = xs_data,
    curve_params = curve,
    noise_params = cond,
    antigen_isos = "HlyE_IgA",
    log_x = TRUE
)

lik_HlyE_IgA # nolint: object_name_linter



```
