## Graph estimated antibody decay curves {.unnumbered}


### Description

Graph estimated antibody decay curves



### Usage

<pre><code class='language-R'>graph.curve.params(
  object,
  antigen_isos = unique(object\$antigen_iso),
  verbose = FALSE,
  quantiles = c(0.1, 0.5, 0.9),
  alpha_samples = 0.3,
  chain_color = TRUE,
  log_x = FALSE,
  log_y = TRUE,
  n_curves = 100,
  iters_to_graph = head(unique(object\$iter), n_curves),
  ...
)
</code></pre>


### Arguments

<table role = "presentation">
<tr><td style = "white-space: collapse; font-family: monospace; vertical-align: top"><code id="object">object</code></td>
<td>
a <code>data.frame()</code> containing MCMC samples of antibody decay curve parameters
</td></tr>
<tr><td style = "white-space: collapse; font-family: monospace; vertical-align: top"><code id="antigen_isos">antigen_isos</code></td>
<td>
antigen isotypes to analyze
(can subset <code>object</code>)
</td></tr>
<tr><td style = "white-space: collapse; font-family: monospace; vertical-align: top"><code id="verbose">verbose</code></td>
<td>
verbose output
</td></tr>
<tr><td style = "white-space: collapse; font-family: monospace; vertical-align: top"><code id="quantiles">quantiles</code></td>
<td>
Optional numeric vector of point-wise (over time)
quantiles to plot (e.g., 10%, 50%, and 90% = <code>c(0.1, 0.5, 0.9)</code>).
If <code>NULL</code>, no quantile lines are shown.
</td></tr>
<tr><td style = "white-space: collapse; font-family: monospace; vertical-align: top"><code id="alpha_samples">alpha_samples</code></td>
<td>
<code>alpha</code> parameter passed to ggplot2::geom_line
(has no effect if <code>iters_to_graph</code> is empty)
</td></tr>
<tr><td style = "white-space: collapse; font-family: monospace; vertical-align: top"><code id="chain_color">chain_color</code></td>
<td>
logical: if TRUE (default), MCMC chain lines
are colored by chain.
If FALSE, all MCMC chain lines are black.
</td></tr>
<tr><td style = "white-space: collapse; font-family: monospace; vertical-align: top"><code id="log_x">log_x</code></td>
<td>
should the x-axis be on a logarithmic scale (<code>TRUE</code>)
or linear scale (<code>FALSE</code>, default)?
</td></tr>
<tr><td style = "white-space: collapse; font-family: monospace; vertical-align: top"><code id="log_y">log_y</code></td>
<td>
should the Y-axis be on a logarithmic scale
(default, <code>TRUE</code>) or linear scale (<code>FALSE</code>)?
</td></tr>
<tr><td style = "white-space: collapse; font-family: monospace; vertical-align: top"><code id="n_curves">n_curves</code></td>
<td>
how many curves to plot (see details).
</td></tr>
<tr><td style = "white-space: collapse; font-family: monospace; vertical-align: top"><code id="iters_to_graph">iters_to_graph</code></td>
<td>
which MCMC iterations in <code>curve_params</code> to plot
(overrides <code>n_curves</code>).
</td></tr>
<tr><td style = "white-space: collapse; font-family: monospace; vertical-align: top"><code id="...">...</code></td>
<td>
not currently used
</td></tr>
</table>


### Details



<h4><code>n_curves</code> and <code>iters_to_graph</code></h4>

In most cases, <code>object</code> will contain too many rows of MCMC
samples for all of these samples to be plotted at once.


<ul>
<li> Setting the  <code>n_curves</code> argument to a value smaller than the
number of rows in <code>curve_params</code> will cause this function to select
the first <code>n_curves</code> rows to graph.

</li>
<li> Setting <code>n_curves</code> larger than the number of rows in ' will
result all curves being plotted.

</li>
<li> If the user directly specifies the <code>iters_to_graph</code> argument,
then <code>n_curves</code> has no effect.

</li></ul>




### Value

a <code>ggplot2::ggplot()</code> object showing the antibody dynamic
kinetics of selected antigen/isotype combinations, with optional posterior
distribution quantile curves.



### Examples
```{r, warning=FALSE, message=FALSE, eval=TRUE}
library("serocalculator")

# Load example dataset
curve <- typhoid_curves_nostrat_100 |>
  dplyr::filter(antigen_iso %in% c("HlyE_IgA", "HlyE_IgG"))

# Plot quantiles without showing all curves
plot1 <- graph.curve.params(curve, n_curves = 0)
print(plot1)

# Plot with additional quantiles and show all curves
plot2 <- graph.curve.params(
  curve,
  n_curves = Inf,
  quantiles = c(0.1, 0.5, 0.9)
)
print(plot2)

# Plot with MCMC chains in black
plot3 <- graph.curve.params(
  curve,
  n_curves = Inf,
  quantiles = c(0.1, 0.5, 0.9),
  chain_color = FALSE
)
print(plot3)


```
