## Calculate log-likelihood {.unnumbered}


### Description

Calculates the log-likelihood of a set of cross-sectional antibody response
data, for a given incidence rate (<code>lambda</code>) value.



### Usage

<pre><code class='language-R'>log_likelihood(
  lambda,
  pop_data,
  curve_params,
  noise_params,
  antigen_isos = get_biomarker_levels(pop_data),
  verbose = FALSE,
  ...
)
</code></pre>


### Arguments

<table role = "presentation">
<tr><td style = "white-space: collapse; font-family: monospace; vertical-align: top"><code id="lambda">lambda</code></td>
<td>
a numeric vector of incidence parameters,
in events per person-year
</td></tr>
<tr><td style = "white-space: collapse; font-family: monospace; vertical-align: top"><code id="pop_data">pop_data</code></td>
<td>
a <code>data.frame()</code> with cross-sectional serology data
by antibody and age, and additional columns
</td></tr>
<tr><td style = "white-space: collapse; font-family: monospace; vertical-align: top"><code id="curve_params">curve_params</code></td>
<td>
a <code>data.frame()</code> containing MCMC samples of parameters
from the Bayesian posterior distribution of a longitudinal decay curve model.
The parameter columns must be named:


<ul>
<li> <code>antigen_iso</code>: a <code>character()</code> vector indicating antigen-isotype
combinations

</li>
<li> <code>iter</code>: an <code>integer()</code> vector indicating MCMC sampling iterations

</li>
<li> <code>y0</code>: baseline antibody level at \$t=0\$ (\$y(t=0)\$)

</li>
<li> <code>y1</code>: antibody peak level (ELISA units)

</li>
<li> <code>t1</code>: duration of infection

</li>
<li> <code>alpha</code>: antibody decay rate
(1/days for the current longitudinal parameter sets)

</li>
<li> <code>r</code>: shape factor of antibody decay

</li></ul>
</td></tr>
<tr><td style = "white-space: collapse; font-family: monospace; vertical-align: top"><code id="noise_params">noise_params</code></td>
<td>
a <code>data.frame()</code> (or <code>tibble::tibble()</code>)
containing the following variables,
specifying noise parameters for each antigen isotype:


<ul>
<li> <code>antigen_iso</code>: antigen isotype whose noise parameters are being specified
on each row

</li>
<li> <code>nu</code>: biological noise

</li>
<li> <code>eps</code>: measurement noise

</li>
<li> <code>y.low</code>: lower limit of detection for the current antigen isotype

</li>
<li> <code>y.high</code>: upper limit of detection for the current antigen isotype

</li></ul>
</td></tr>
<tr><td style = "white-space: collapse; font-family: monospace; vertical-align: top"><code id="antigen_isos">antigen_isos</code></td>
<td>
Character vector listing one or more antigen isotypes.
Values must match <code>pop_data</code>.
</td></tr>
<tr><td style = "white-space: collapse; font-family: monospace; vertical-align: top"><code id="verbose">verbose</code></td>
<td>
logical: if TRUE, print verbose log information to console
</td></tr>
<tr><td style = "white-space: collapse; font-family: monospace; vertical-align: top"><code id="...">...</code></td>
<td>
additional arguments passed to other functions
(not currently used).
</td></tr>
</table>


### Value

the log-likelihood of the data with the current parameter values



### Examples
```{r, warning=FALSE, message=FALSE, eval=TRUE}
library("serocalculator")

library(dplyr)
library(tibble)

# Load cross-sectional data
xs_data <-
  sees_pop_data_pk_100

# Load curve parameters and subset for the purposes of this example
curve <-
  typhoid_curves_nostrat_100 %>%
  filter(antigen_iso %in% c("HlyE_IgA", "HlyE_IgG"))

# Load noise params
cond <- tibble(
  antigen_iso = c("HlyE_IgG", "HlyE_IgA"),
  nu = c(0.5, 0.5), # Biologic noise (nu)
  eps = c(0, 0), # M noise (eps)
  y.low = c(1, 1), # low cutoff (llod)
  y.high = c(5e6, 5e6)
) # high cutoff (y.high)

# Calculate log-likelihood
ll_AG <- log_likelihood(
  pop_data = xs_data,
  curve_params = curve,
  noise_params = cond,
  antigen_isos = c("HlyE_IgG", "HlyE_IgA"),
  lambda = 0.1
) %>% print()



```
