#' Plot method for `summary.seroincidence.by` objects
#'
#' @param object
#' a `summary.seroincidence.by` object
#' (generated by applying the `summary()`
#' method to the output of [estimate_scr_by()]).
#' @param xvar the name of a stratifying variable in `object`
#' @param ylab the name of a second stratifying variable in `object` (e.g., "catchment")
#' @param title a title for the final plot
#' @param xlab a label for the x axis of the final plot
#' @param fill_lab fill label
#' @param fill_palette define the color palette for bar fill
#' @param fill_var the name of the variable used for fill color (e.g., "Country")
#' @param alpha transparency for the points in the graph
#' (1 = no transparency, 0 = fully transparent)
#' @param shape shape argument for `geom_point()`
#' @param dodge_width width for jitter
#' @param CIs [logical], if `TRUE`, add CI error bars
#' @param ... unused
#' @param type
#' [character] string indicating which type of plot to generate.
#' The implemented options are:
#' - `"scatter"`: calls [strat_ests_scatterplot()] to generate a scatterplot
#' -  `"bar"`: calls `strat_ests_barplot()` to generate a barplot
#' @inheritDotParams strat_ests_scatterplot

#'
#' @return a [ggplot2::ggplot()] object
#' @export
#' @examples
#'
#' library(dplyr)
#' library(ggplot2)
#'
#' xs_data <-
#'   sees_pop_data_pk_100
#'
#' curve <-
#'   typhoid_curves_nostrat_100 %>%
#'   filter(antigen_iso %in% c("HlyE_IgA", "HlyE_IgG"))
#'
#' noise <-
#'   example_noise_params_pk.rda
#'
#' est2 <- estimate_scr_by(
#'   strata = c("catchment", "ageCat"),
#'   pop_data = xs_data,
#'   curve_params = curve,
#'   noise_params = noise,
#'   curve_strata_varnames= NULL,
#'   noise_strata_varnames = NULL,
#'   antigen_isos = c("HlyE_IgG", "HlyE_IgA"),
#'   num_cores = 2 # Allow for parallel processing to decrease run time
#' )
#'
#' est2sum <- summary(est2)
#'
#' autoplot(est2sum,
#'     type ="scatter",
#'     xvar = "ageCat",
#'     color_var = "catchment",
#'     CIs = TRUE,
#'     group_var = "catchment")
#'
#' autoplot(est2sum, "ageCat", type = "scatter", color_var = "catchment", CIs = TRUE, group_var = "catchment")
#'
#' autoplot(est2sum, "ageCat", type = "bar", fill_var = "catchment")
#'
autoplot.summary.seroincidence.by <- function(
    object,
    type = "scatter",
    xvar,
    fill_var,
    alpha = .7,
    shape = 1,
    dodge_width = 0.001,
    CIs = FALSE,
    title = "Seroconversion Rate by Group",
    xlab = "Seroconversion rate per 1000 person-years",
    ylab = "Stratification Variable",
    fill_lab = fill_var,
    fill_palette = NULL,
    ...
) {

  # Check if xvar exists in the dataset
  if (!is.element(xvar, names(object))) {
    cli::cli_abort(
      class = "unavailable_xvar",
      message = c(
        "The variable `{xvar}` specified by argument `xvar` does not exist in `object`.",
        "Please choose a column that exists in `object`."
      )
    )
  }

  # Check if fill_var exists when type = "bar"
  if (type == "bar" && !is.null(fill_var) && !is.element(fill_var, names(object))) {
    cli::cli_abort(
      class = "unavailable_fill_var",
      message = c(
        "The variable `{fill_var}` specified by argument `fill_var` does not exist in `object`.",
        "Please choose a column that exists in `object`."
      )
    )
  }

  if (type == "scatter") {
    plot1 <- strat_ests_scatterplot(object, ...)

  } else if (type == "bar") {
    plot1 <- ggplot2::ggplot(object, ggplot2::aes(
      y = forcats::fct_rev(.data[[xvar]]),
      x = .data$incidence.rate * 1000,
      fill = if (!is.null(fill_var)) .data[[fill_var]] else NULL
    )) +
      ggplot2::geom_bar(stat = "identity", position = ggplot2::position_dodge(), show.legend = !is.null(fill_var), alpha = alpha) +
      ggplot2::labs(
        title = title,
        x = xlab,
        y = ylab,
        fill = fill_lab
      ) +
      ggplot2::theme_linedraw() +
      ggplot2::theme(
        axis.text.y = ggplot2::element_text(size = 11),
        axis.text.x = ggplot2::element_text(size = 11)
      ) +
      ggplot2::scale_x_continuous(expand = c(0, 10))
  } else {
    cli::cli_abort(
      c(
        "Invalid plot `type` specified: {.str {type}}.",
        "i" = "Please choose either 'scatter' or 'bar'."
      )
    )
  }

  return(plot1)
}
