#' Plot method for `summary.seroincidence.by` objects
#'
#' @param object
#' a `summary.seroincidence.by` object
#' (generated by applying the `summary()`
#' method to the output of [est.incidence.by()]).
#' @param xvar the name of a stratifying variable in `object`
#' @param alpha transparency for the points in the graph
#' (1 = no transparency, 0 = fully transparent)
#' @param shape shape argument for `geom_point()`
#' @param dodge_width width for jitter
#' @param CIs [logical], if `TRUE`, add CI error bars
#' @param ... unused
#'
#' @return a [ggplot2::ggplot()] object
#' @export
#' @examples
#'
#' library(dplyr)
#' library(ggplot2)
#'
#' xs_data <-
#'   sees_pop_data_pk_100
#'
#' curve <-
#'   typhoid_curves_nostrat_100 %>%
#'   filter(antigen_iso %in% c("HlyE_IgA", "HlyE_IgG"))
#'
#' noise <-
#'   example_noise_params_pk
#'
#' est2 <- est.incidence.by(
#'   strata = c("catchment"),
#'   pop_data = xs_data,
#'   curve_params = curve,
#'   noise_params = noise,
#'   curve_strata_varnames= NULL,
#'   noise_strata_varnames = NULL,
#'   antigen_isos = c("HlyE_IgG", "HlyE_IgA"),
#'   num_cores = 8 # Allow for parallel processing to decrease run time
#' )
#'
#' est2sum <- summary(est2)
#'
#' autoplot(est2sum, "catchment")
#'
autoplot.summary.seroincidence.by <- function(
    object,
    xvar,
    alpha = .7,
    shape = 1,
    dodge_width = 0.001,
    CIs = FALSE,
    ...) {

  plot1 <-
    object |>
    ggplot2::ggplot() +
    ggplot2::aes(
      x = get(xvar),
      y = .data$incidence.rate,
      col = .data$nlm.convergence.code
    ) +
    ggplot2::xlab(xvar) +
    ggplot2::ylab("Estimated incidence rate") +
    ggplot2::theme_linedraw() +
    ggplot2::theme(
      panel.grid.minor.x = ggplot2::element_blank(),
      panel.grid.minor.y = ggplot2::element_blank()) +
    ggplot2::expand_limits(y = 0) +
    ggplot2::labs(col = "`nlm()` convergence code") +
    ggplot2::theme(legend.position = "bottom")

  if(CIs) {
    plot1 <- plot1 +
      ggplot2::geom_pointrange(
        alpha = alpha,
        position = ggplot2::position_dodge2(width = dodge_width),
        aes(ymin = .data$CI.lwr, ymax = .data$CI.upr)
      )

  } else {
    plot1 <- plot1 +
      ggplot2::geom_point(
      position = ggplot2::position_dodge2(width = dodge_width),
      shape = shape,
      alpha = alpha
    )

  }

  return(plot1)

}
