#' Plot method for `summary.estimate_scr_by` objects
#'
#' @param object
#' a `summary.seroincidence.by` object
#' (generated by applying the `summary()`
#' method to the output of [estimate_scr_by()]).
#' @param xvar the name of a stratifying variable in `object` (e.g., "ageCat")
#' @param fill_var the name of the variable used for fill color (e.g., "Country")
#' @param alpha transparency for the bars (1 = no transparency, 0 = fully transparent)
#' @param CIs [logical], if `TRUE`, add horizontal CI error bars
#' @param ... unused
#'
#' @return a [ggplot2::ggplot()] object
#' @export
#' @examples
#'
#' library(dplyr)
#' library(ggplot2)
#'
#' xs_data <-
#'   sees_pop_data_pk_100
#'
#' curve <-
#'   typhoid_curves_nostrat_100 %>%
#'   filter(antigen_iso %in% c("HlyE_IgA", "HlyE_IgG"))
#'
#' noise <-
#'   example_noise_params_pk
#'
#' est_catchment_age <- estimate_scr_by(
#' strata = c("catchment", "ageCat"),
#' pop_data = xs_data,
#' curve_params = curve,
#' curve_strata_varnames = NULL,
#' noise_params = noise,
#' noise_strata_varnames = "catchment",
#' antigen_isos = c("HlyE_IgG", "HlyE_IgA"),
#' num_cores = 8 # Allow for parallel processing to decrease run time
#' )
#'
#' est_catchment_age_sum <- summary(est_catchment_age)
#'
#' autoplot.summary.estimate_scr_by(
#'   est_catchment_age_sum,
#'   "ageCat",
#'   fill_var = "catchment"
#' )
#'
#'
autoplot.summary.estimate_scr_by <- function(
  object,
  xvar,
  fill_var,
    alpha = 0.7,
    CIs = FALSE,
    title = "Seroconversion Rate by Group",
    xlab = "Seroconversion rate per 1000 person-years",
    ylab = "Stratification Variable",
    fill_palette = NULL,
    ...
  ) {
    if (!is.element(xvar, names(object))) {
      cli::cli_abort(
        class = "unavailable_xvar",
        message = c(
          "The variable `{xvar}` specified by argument `xvar` does not exist in `object`.",
          "Please choose a column that exists in `object`."
        )
      )
    }

  if (!is.element(fill_var, names(object))) {
      cli::cli_abort(
        class = "unavailable_fill_var",
        message = c(
          "The variable `{fill_var}` specified by argument `fill_var` does not exist in `object`.",
          "Please choose a column that exists in `object`."
        )
      )
    }

  plot1 <-
      ggplot2::ggplot(object, ggplot2::aes(
        y = forcats::fct_rev(.data[[xvar]]),
        x = .data$incidence.rate * 1000,
        fill = .data[[fill_var]]
      )) +
      ggplot2::geom_bar(stat = "identity", position = ggplot2::position_dodge(), show.legend = TRUE, alpha = alpha) + {

        if (CIs) ggplot2::geom_errorbar(
          aes(xmin = .data$CI.lwr * 1000, xmax = .data$CI.upr * 1000),
          position = ggplot2::position_dodge(width = 0.9),
          width = 0.2
        )
      } +
      ggplot2::labs(
        title = title,
        x = xlab,
        y = ylab,
        fill = fill_lab
      ) +
      ggplot2::theme_linedraw() +
      ggplot2::theme(
        axis.text.y = ggplot2::element_text(size = 11),
        axis.text.x = ggplot2::element_text(size = 11)
      ) +
      ggplot2::scale_x_continuous(expand = c(0, 10))

  if (!is.null(fill_palette)) {
      plot1 <- plot1 + ggplot2::scale_fill_manual(values = fill_palette)
    }

  return(plot1)
}
