#' Plot method for `summary.seroincidence.ests` objects
#'
#' @param object a `summary.seroincidence.ests` object (generated by applying the `summary()` method to the output of [est.incidence.by()]).
#' @param alpha transparency for the points in the graph (1 = no transparency, 0 = fully transparent)
#'
#' @return a [ggplot2::ggplot()] object
#' @export
#'
plot.summary.seroincidence.ests = function(object, alpha = .9)
{
  object |>
  ggplot2::ggplot(ggplot2::aes(x = lambda.sim, y = incidence.rate)) +
    ggplot2::geom_point(alpha = alpha) +
    ggplot2::xlab("Simulated incidence rate") +
    ggplot2::ylab("Estimated incidence rate") +
    ggplot2::theme_bw() +
    ggplot2::geom_abline(aes(intercept = 0, slope = 1, col = "x=y")) +
    ggplot2::expand_limits(x = 0,y = 0) +
    ggplot2::labs(col = "")
}
