#' Plot method for `summary.seroincidence.by` objects
#'
#' @param x a `summary.seroincidence.by` object (generated by applying the `summary()` method to the output of [est.incidence.by()]).
#' @param xvar the name of a stratifying variable in `object`
#' @param alpha transparency for the points in the graph (1 = no transparency, 0 = fully transparent)
#' @param ... unused
#'
#' @return a [ggplot2::ggplot()] object
#' @export
#'
plot.summary.seroincidence.by = function(
    x,
    xvar,
    alpha = .9,
    ...)
{
  x |>
  ggplot2::ggplot(ggplot2::aes(x = get(xvar), y = .data$incidence.rate)) +
    ggplot2::geom_point(alpha = alpha) +
    ggplot2::xlab(xvar) +
    ggplot2::ylab("Estimated incidence rate") +
    ggplot2::theme_bw() +
    ggplot2::geom_abline(ggplot2::aes(intercept = 0, slope = 1, col = "x=y")) +
    ggplot2::expand_limits(x = 0,y = 0) +
    ggplot2::labs(col = "")
}
