#' Barplot method for `summary.seroincidence.by` objects
#'
#' @param object
#' a `summary.seroincidence.by` object
#' (generated by applying the `summary()`
#' method to the output of [estimate_scr_by()]).
#' @param xvar the name of a stratifying variable in `object`
#' @param alpha transparency for the points in the graph
#' (1 = no transparency, 0 = fully transparent)
#' @param shape shape argument for `geom_point()`
#' @param dodge_width width for jitter
#' @param CIs [logical], if `TRUE`, add CI error bars
#' @param color_var [character] which variable in `object` to use
#' to determine bar color
#' @param ... unused
#'
#' @return a [ggplot2::ggplot()] object
#' @export
#' @keywords internal
#'
strat_ests_barplot <- function(
    object,
    xvar,
    color_var,
    alpha = 0.7,
    CIs = FALSE,
    title = "Seroconversion Rate by Group",
    xlab = "Seroconversion rate per 1000 person-years",
    ylab = "Stratification Variable",
    fill_lab,
    fill_palette = NULL,
    ...
) {

  color_label <- object[[color_var]] |> labelled::get_label_attribute()
  if (is.null(color_label)) color_label <- color_var

  plot1 <- ggplot2::ggplot(object, ggplot2::aes(
    y = forcats::fct_rev(.data[[xvar]]),
    x = .data$incidence.rate * 1000,
    fill = if (!is.null(color_var)) .data[[color_var]] else NULL
  )) +
    ggplot2::geom_bar(stat = "identity", position = ggplot2::position_dodge(), show.legend = !is.null(color_var), alpha = alpha) +
    ggplot2::labs(
      title = title,
      x = xlab,
      y = ylab,
      fill = fill_lab
    ) +
    ggplot2::theme_linedraw() +
    ggplot2::theme(
      axis.text.y = ggplot2::element_text(size = 11),
      axis.text.x = ggplot2::element_text(size = 11)
    ) +
    ggplot2::scale_x_continuous(expand = c(0, 10))

  return(plot1)

}
