---
name: Spellcheck

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check:
    runs-on: ubuntu-latest
    name: Spellcheck
    container:
      image: rocker/tidyverse:latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: any::spelling

      - name: Run Spelling Check Test
        uses: insightsengineering/r-spellcheck-action@v3.0.2
