name: Check NEWS.md Changelog
on:
  pull_request:
    types: [assigned, opened, synchronize, reopened, labeled, unlabeled]
    branches:
      - main
jobs:
  Check-Changelog:
    name: Check Changelog Action
    runs-on: ubuntu-20.04
    steps:
      - uses: UCD-SERG/changelog-check-action@v2
        with:
          changelog: NEWS.md
