name: Check NEWS.md Changelog

on:
  pull_request:
    types: [assigned, opened, synchronize, reopened, labeled, unlabeled]
    branches:
      - main

jobs:
  check:
    uses: d-morrison/gha/.github/workflows/check-news.yml@v1
